import Head from "next/head";
import styles from "../styles/Home.module.css";

// import { getServerSideProps } from "./server/fetchOtherData";
import { useEffect, useState } from "react";
import ProfileCard from "../components/profileCard/ProfileCard";
import CardsList from "../components/cardsList/CardsList";

export default function Home({ data }) {
  const [profileData, setProfileData] = useState();

  useEffect(() => {
    const fetchData = async () => {
      const response = await fetch(
        "https://europe-west3-clozer-bc97fb95.cloudfunctions.net/idols?slug=AssignmentUser"
      );
      if (!response.ok) {
        throw new Error(`HTTP error! status: ${response.status}`);
      }
      const result = await response.json();
      setProfileData(result);
    };

    fetchData().catch((e) => {
      console.error("An error occurred while fetching the data: ", e);
    });
  }, []);


  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.min.css"
        />
        <link
          rel="stylesheet"
          type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick-theme.min.css"
        />
      </Head>

      <main className={styles.main}>
        <ProfileCard profile={profileData} />
        <CardsList data={data} />
      </main>

      <footer className={styles.footer}>Footer</footer>
    </div>
  );
}

// export { getServerSideProps };

export async function getServerSideProps() {
  // Fetch data from external API
  const res = await fetch(`https://europe-west3-clozer-bc97fb95.cloudfunctions.net/idols/RKAs4VxFlOZ1q2uWhD6UIYgybuj2/tabs?isEditor=false`)
  const data = await res.json()
 
  // Pass data to the page via props
  return { props: { data } }
}